image: node:10.15.3

pipelines:
  default:
    - step:
        name: Test Web Form
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y protobuf-compiler
          - >
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
              sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
              apt-get update && \
              apt-get install -y google-chrome-stable xvfb procps
          - git submodule update --init --recursive
          - echo $ENVIRONMENT_DEV_TS > src/environments/environment.ts
          - npm install
          - npm run test:ci
          - npm run e2e:ci

  branches:
    feature/bitbucket-pipelines:
        - step:
            name: Test and deploy Web Form
            deployment: test
            script:
              - apt-get update
              - apt install -y protobuf-compiler
              - >
                wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
                  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                  apt-get update && \
                  apt-get install -y google-chrome-stable xvfb procps
              - git submodule update --init --recursive
              - echo $ENVIRONMENT_DEV_TS > src/environments/environment.ts
              - echo $ENVIRONMENT_TS > src/environments/environment.prod.ts
              - npm install
              - npm run test:ci
              - npm run e2e:ci
              - npm run build:prod
              - pipe: atlassian/firebase-deploy:0.3.0
                variables:
                  FIREBASE_TOKEN: '$FIREBASE_TOKEN_CI'
